import type { Task } from './model';
export const initialTasks: Task[] = [
  {
    id: '1',
    title: '인벤토리 UI 구현',
    project: 'Forest of Echoes',
    scope: 'unity',
    status: 'todo',
    priority: '높음',
    tag: '기능',
  },
  {
    id: '2',
    title: '환경 사운드 에셋 정리',
    project: 'Forest of Echoes',
    scope: 'unity',
    status: 'todo',
    priority: '보통',
    tag: '에셋',
  },
  {
    id: '3',
    title: '캐릭터 이동 로직 개선',
    project: 'Forest of Echoes',
    scope: 'unity',
    status: 'doing',
    priority: '높음',
    tag: '개선',
  },
  {
    id: '4',
    title: '레벨 생성 시스템 설계',
    project: 'Orbit Runner',
    scope: 'unity',
    status: 'doing',
    priority: '보통',
    tag: '기능',
  },
  {
    id: '5',
    title: '카메라 추적 버그 수정',
    project: 'Forest of Echoes',
    scope: 'unity',
    status: 'done',
    priority: '보통',
    tag: '버그',
  },
  {
    id: '6',
    title: '인증 API 테스트',
    project: 'Devspace API',
    scope: 'server',
    status: 'doing',
    priority: '높음',
    tag: '테스트',
  },
  {
    id: '7',
    title: '배포 파이프라인 구성',
    project: 'Devspace API',
    scope: 'server',
    status: 'todo',
    priority: '보통',
    tag: '운영',
  },
];
